# Generated by Django 4.0.3 on 2022-06-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Address', models.TextField()),
                ('Phone', models.TextField()),
                ('Clinic', models.TextField()),
                ('Notes', models.TextField()),
            ],
        ),
    ]
