# Generated by Django 4.0.3 on 2022-06-05 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clinic_Name', models.TextField()),
                ('Num_Bookings', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appointments.report'),
        ),
    ]
