# Generated by Django 4.0.3 on 2022-06-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_report_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='Id',
        ),
    ]
