# Generated by Django 4.0.3 on 2022-06-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_form_id_alter_form_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Num_Bookings',
        ),
    ]
