# Generated by Django 4.0.3 on 2022-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_form_id_alter_report_num_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
