# Generated by Django 4.0.3 on 2022-06-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_form_id_alter_report_num_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='Num_Bookings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.form'),
        ),
    ]
