# Generated by Django 4.0.3 on 2022-06-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_contact_rename_id_form_id_remove_report_clinic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Clinic_Name',
            field=models.TextField(default='Bs'),
        ),
        migrations.AddField(
            model_name='report',
            name='Num_Bookings',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='form',
            name='Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appointments.report'),
        ),
    ]
