# Generated by Django 4.0.3 on 2022-06-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Id',
            new_name='increement',
        ),
    ]
