# Generated by Django 4.0.3 on 2022-06-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_rename_id_form_increement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='increement',
            new_name='Id',
        ),
    ]
