# Generated by Django 4.0.3 on 2022-06-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
