# Generated by Django 4.0.3 on 2022-06-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_alter_form_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='id',
            new_name='Id',
        ),
    ]
